Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df.plot.barh()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/var/folders/qt/qy37fy6s3c1553y2k74063pr0000gn/T/ipykernel_49126/610630747.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mdf[0m[0;34m.[0m[0mplot[0m[0;34m.[0m[0mbarh[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/plotting/_core.py[0m in [0;36mbarh[0;34m(self, x, y, **kwargs)[0m
[1;32m   1197[0m         [0mother[0m [0maxis[0m [0mrepresents[0m [0ma[0m [0mmeasured[0m [0mvalue[0m[0;34m.[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1198[0m         """
[0;32m-> 1199[0;31m         [0;32mreturn[0m [0mself[0m[0;34m([0m[0mkind[0m[0;34m=[0m[0;34m"barh"[0m[0;34m,[0m [0mx[0m[0;34m=[0m[0mx[0m[0;34m,[0m [0my[0m[0;34m=[0m[0my[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1200[0m [0;34m[0m[0m
[1;32m   1201[0m     [0;32mdef[0m [0mbox[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mby[0m[0;34m=[0m[0;32mNone[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/plotting/_core.py[0m in [0;36m__call__[0;34m(self, *args, **kwargs)[0m
[1;32m    953[0m                     [0mdata[0m[0;34m.[0m[0mcolumns[0m [0;34m=[0m [0mlabel_name[0m[0;34m[0m[0;34m[0m[0m
[1;32m    954[0m [0;34m[0m[0m
[0;32m--> 955[0;31m         [0;32mreturn[0m [0mplot_backend[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mdata[0m[0;34m,[0m [0mkind[0m[0;34m=[0m[0mkind[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    956[0m [0;34m[0m[0m
[1;32m    957[0m     [0m__call__[0m[0;34m.[0m[0m__doc__[0m [0;34m=[0m [0m__doc__[0m[0;34m[0m[0;34m[0m[0m

[0;32m/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/plotting/_matplotlib/__init__.py[0m in [0;36mplot[0;34m(data, kind, **kwargs)[0m
[1;32m     59[0m             [0mkwargs[0m[0;34m[[0m[0;34m"ax"[0m[0;34m][0m [0;34m=[0m [0mgetattr[0m[0;34m([0m[0max[0m[0;34m,[0m [0;34m"left_ax"[0m[0;34m,[0m [0max[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     60[0m     [0mplot_obj[0m [0;34m=[0m [0mPLOT_CLASSES[0m[0;34m[[0m[0mkind[0m[0;34m][0m[0;34m([0m[0mdata[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 61[0;31m     [0mplot_obj[0m[0;34m.[0m[0mgenerate[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     62[0m     [0mplot_obj[0m[0;34m.[0m[0mdraw[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     63[0m     [0;32mreturn[0m [0mplot_obj[0m[0;34m.[0m[0mresult[0m[0;34m[0m[0;34m[0m[0m

[0;32m/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/plotting/_matplotlib/core.py[0m in [0;36mgenerate[0;34m(self)[0m
[1;32m    278[0m         [0mself[0m[0;34m.[0m[0m_compute_plot_data[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    279[0m         [0mself[0m[0;34m.[0m[0m_setup_subplots[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 280[0;31m         [0mself[0m[0;34m.[0m[0m_make_plot[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    281[0m         [0mself[0m[0;34m.[0m[0m_add_table[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    282[0m         [0mself[0m[0;34m.[0m[0m_make_legend[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/plotting/_matplotlib/core.py[0m in [0;36m_make_plot[0;34m(self)[0m
[1;32m   1435[0m             [0;32melif[0m [0mself[0m[0;34m.[0m[0morientation[0m [0;34m==[0m [0;34m"horizontal"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1436[0m                 [0max[0m[0;34m.[0m[0myaxis[0m[0;34m.[0m[0mupdate_units[0m[0;34m([0m[0mself[0m[0;34m.[0m[0max_index[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1437[0;31m                 [0mself[0m[0;34m.[0m[0mtick_pos[0m [0;34m=[0m [0max[0m[0;34m.[0m[0mconvert_yunits[0m[0;34m([0m[0mself[0m[0;34m.[0m[0max_index[0m[0;34m)[0m[0;34m.[0m[0mastype[0m[0;34m([0m[0mnp[0m[0;34m.[0m[0mint[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1438[0m             [0mself[0m[0;34m.[0m[0max_pos[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mtick_pos[0m [0;34m-[0m [0mself[0m[0;34m.[0m[0mtickoffset[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1439[0m [0;34m[0m[0m

[0;32m/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/__init__.py[0m in [0;36m__getattr__[0;34m(attr)[0m
[1;32m    303[0m [0;34m[0m[0m
[1;32m    304[0m         [0;32mif[0m [0mattr[0m [0;32min[0m [0m__former_attrs__[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 305[0;31m             [0;32mraise[0m [0mAttributeError[0m[0;34m([0m[0m__former_attrs__[0m[0;34m[[0m[0mattr[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    306[0m [0;34m[0m[0m
[1;32m    307[0m         [0;31m# Importing Tester requires importing all of UnitTest which is not a[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

